### ISSUE TITLE
IC logs out for inactivity

### ISSUE THREAD

**Issue by lewisc5** [minima-global/Minima#246] opened 2021-06-04 16:57 UTC
The IC app logs me out about every hour or so "for inactivity" even if my node is still running and my phone has another Minima-related screen up. 
![Screenshot_20210604-104533](https://user-images.githubusercontent.com/85313270/120836577-b83de480-c533-11eb-80fb-4848e427efb6.png)

**Comment by eliasnemr** [comment] 2021-06-04 18:36
Hi Lewis,

This is intentional.  It's for security reasons.  You're logged out every hour & 30 mins if you're logged in the background.  However that doesn't mean you're not going to make your collection if your node is online & running.

Thanks,

Elias

**Comment by eurobuddha** [comment] 2021-06-06 15:13
@eliasnemr @glowkeeper can we close this, feature not a bug?

**Comment by lewisc5** [comment] 2021-06-06 15:19
Yeah, I suppose it’s a feature. Do I need to close it or can you guys?

**Closed** 2021-06-06 17:42 UTC
Labels: bug

**Comment by eurobuddha** [comment] 2021-06-06 20:59
I have closed it Lewis ty

Sent from Mail for Windows 10

**Comment by glowkeeper** [comment] 2021-06-07 08:42
Just a note on this - @lewisc5 - there's no _suppose_ about this! As @eliasnemr explained, it's a necessary security feature; indeed, you'll find your banking app' will act similarly. In fact, I wanted to have this activated after 15 minutes, to keep it super secure! Luckily for you, @spartacusrex99 and @eliasnemr argues for what we have now ;)
