### ISSUE TITLE
Syntaxerror, unexpected end of Json inpus

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#249] opened 2021-06-05 19:35 UTC
Hello Support,

Issue Impact: Critical Issue

Device Manufacturer: Samsung
Device Model: Galaxi S20+ 5G
Divice OS: Android 
Device OS Version: 11
Application Version: 3.1
What Happend? Received a NFT token 
What Did You Expect To Happen: to open my wallet and see the balance with the NFT token
Steps to Recreate Issue: closed the app and taps, opend it again, same issue. Closed app and windows again, reboot, opened app, same issue. Closed app and windows, open app again, restore DB is taking to long.

https://user-images.githubusercontent.com/73369734/120903295-b06e6500-c645-11eb-8b93-5c2bacc6b64b.mp4

[Euroboddha NFT Bom.txt](https://github.com/minima-global/Minima/files/6603129/Euroboddha.NFT.Bom.txt)

**Comment by eurobuddha** [comment] 2021-06-06 18:13
duplicate of #248

**Comment by eurobuddha** [comment] 2021-06-14 09:49
duplicate of #248

**Closed by eurobuddha** 2021-06-14 09:49 UTC
Labels: bug
