### ISSUE TITLE
Minima Has Stopped Error

### ISSUE THREAD

**Issue by jonomacx** [minima-global/Minima#80] opened 2021-02-09 15:50 UTC
Have installed latest update: 0.97.10 
Still encountering the same issue as #9  
Error message encountered immediately after install:  "Minima has stopped"
I then click on "Open app again" and then it states "Minima keeps stopping"

Samsung A8
Android 8.0.0
Samsung Experience: 9.0

**Comment by eurobuddha** [comment] 2021-02-09 16:27
duplicate of #9

**Comment by eurobuddha** [comment] 2021-05-06 17:55
fixed in 98.15

**Closed by eurobuddha** 2021-05-06 17:55 UTC
Labels: bug, duplicate
