### ISSUE TITLE
Incentive missed

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#274] opened 2021-06-11 09:55 UTC
Issue Impact: Major Issue

Device Manufacturer: Samsung
Device Model: Galaxy S20+ 5G
Device OS: Android
Device version:11
Application Version: 3.1
What Happened?  Ive missed the intensive timer, I was logged out of intensive app but apk was connected and in never sleeping mode. 
What Did You Expect To Happen: That is was running fine and that, and that, despite not being logged into the incentive app, I would still receive the tokens. The app should be able to view the history and still perform the action
Steps to Recreate Issue: Can't do that now, will have to wait till the next date that is coming up.

I see there is a a gab from 07:29:33 till 10:50:24 in the log
Also the time that it was going to be released was 11-6-2021 at 11.36, see photo. Had that one luckily. Got the missed notification 20 min before that, that was the time a looked at it.

![Screenshot_20210609-182337_Brave](https://user-images.githubusercontent.com/73369734/121667325-73bdc600-caaa-11eb-9539-06f17890b5bf.jpg)

![Screenshot_20210611-111453_Brave](https://user-images.githubusercontent.com/73369734/121665066-6f90a900-caa8-11eb-9ee3-1513e7d58a5b.jpg)
![Screenshot_20210611-104443_Brave](https://user-images.githubusercontent.com/73369734/121665074-71f30300-caa8-11eb-9e4e-ed1a03226f13.jpg)
[Incentive missed 2.txt](https://github.com/minima-global/Minima/files/6637411/Incentive.missed.2.txt)

**Comment by glowkeeper** [comment] 2021-06-11 12:40
Duplicate of #273

**Comment by glowkeeper** [comment] 2021-06-11 12:42
The server was sending out the incorrect block window - it will be fixed for the next collection, but please watch out for a message from the Minima Community Team as to the next steps...

**Closed** 2022-03-03 14:46 UTC
Labels: bug
