### ISSUE TITLE
Transactions fail sending a token

### ISSUE THREAD

**Issue by BoldorXL** [minima-global/Minima#259] opened 2021-06-07 16:44 UTC
Issue Impact: Minor Issue 

Device Manufacturer: Samsung
Device Model: Galaxi S20+ 5G
Divice OS: Android 
Device OS Version: 11
Application Version: 3.1
What Happend? When sending a token I got a fail
What Did You Expect To Happen: I could send the token
Steps to Recreate Issue: filling in the send in form and press send, confirm 
Did send 3 tokens after that and all went well.
![Screenshot_20210607-182719_Brave](https://user-images.githubusercontent.com/73369734/121058093-46c69600-c7c0-11eb-97c0-a65a09efd2db.jpg)
[Transaction fail 7-6-21.txt](https://github.com/minima-global/Minima/files/6610704/Transaction.fail.7-6-21.txt)

**Comment by eurobuddha** [comment] 2021-06-07 18:01
Duplicate of #247

**Closed** 2021-09-19 14:09 UTC
Labels: bug, duplicate
